---
- import_tasks: common.yml

- name: "Start zabbix wrapper container"
  docker_container:
    name: indigo-zabbix-wrapper
    image: "{{monitoring_zabbix_wrapper_image}}"
    env:
      ZABBIX_URL: "{{monitoring_zabbix_url}}"
      ZABBIX_USERNAME: "{{monitoring_zabbix_username}}"
      ZABBIX_PASSWORD: "{{monitoring_zabbix_password}}"
    restart_policy: always
    network_mode: bridge
    published_ports:
       - 8082:8080

- import_tasks: install-probes.yml

