---
- name: "Check input variables"
  fail:
    msg: "Change the password: you are using <<changeit>> as value for one or more variables (monitoring_mysql_root_password, monitoring_mysql_password) "
  when: item == "changeit"
  with_items:
    - "{{monitoring_mysql_root_password}}"
    - "{{monitoring_mysql_password}}"


- name: "Check input variables"
  fail:
    msg: "Change the password: you are using <<zabbix>> as value for Zabbix Admin password! Change the value of the variable monitoring_zabbix_password"
  when: item == "zabbix"
  with_items:
    - "{{monitoring_zabbix_password}}"

- name: "create directory path to store persistent files"
  file:
    path: "{{ monitoring_mysql_data_path }}"
    state: directory
    mode: 0755

- import_tasks: common.yml

- name: "Check if the web api are available"
  run_once: true
  uri:
     url: "{{monitoring_zabbix_url}}"
     validate_certs: "no"
     method: POST
     status_code: 200
     headers:
        Content-Type: "application/json-rpc"
     body: '{ "jsonrpc": "2.0", "method": "apiinfo.version", "params": [], "id": 1 }'
     body_format: json
     return_content: yes
  register: response
  until: response.json is defined and response.json.result is defined and response.json.result == "3.2.11"
  retries: 60
  delay: 60


- name: "Reset zabbix Admin password"
  command: "docker-compose exec zabbix-db mysql -u {{monitoring_mysql_user}} -p{{monitoring_mysql_password}} zabbix -e \"update users set passwd=md5('{{monitoring_zabbix_password}}') where alias='{{monitoring_zabbix_username}}'\""
  args:
    chdir: "{{ monitoring_conf_dir }}"



