---
# defaults file for indigopaas

monitoring_conf_dir: /etc/monitoring
monitoring_zabbix_conf_dir: /etc/zabbix

monitoring_mysql_user: zabbix
monitoring_mysql_password: changeit
monitoring_mysql_root_password: changeit


monitoring_zabbix_wrapper_image: indigodatacloud/zabbix-wrapper:indigo_2 
monitoring_zabbix_url: "http://{{monitoring_server_host}}/api_jsonrpc.php"
monitoring_zabbix_username: Admin
monitoring_zabbix_password: zabbix

monitoring_agent_host: "{{ansible_default_ipv4.address}}"
monitoring_server_host: "{{ groups['monitoring-server'][0] }}"

monitoring_openstack_probe_deb: http://repo.indigo-datacloud.eu/repository/indigo/2/ubuntu/dists/xenial-updates/main/binary-amd64/openstack-zabbix-probe-1.2.deb
monitoring_cmdb_location: "https://{{ groups['proxy'][0] }}/cmdb" 
monitoring_iam_token_url: https://endpoint/token
monitoring_iam_username:
monitoring_iam_password:
monitoring_iam_client:
monitoring_iam_secret:
monitoring_openstack_project:
monitoring_iam_organization_name: 

zabbix_template_list: [ 'zbx_mesos_template.xml', 'zbx_openstack_template.xml' ]
