galaxy_info:
  author: marica.antonacci@gmail.com
  description: Install docker engine
  company: INDIGO-DataCloud
  license: Apache
  min_ansible_version: 2.5
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - docker

dependencies:
  - role: geerlingguy.pip
    vars:
      pip_package: "{{ docker_pip_package }}"
      pip_install_packages: 
        - "{{ 'docker' if ansible_version.minor >= 6 else 'docker-py' }}"
  
