---
# tasks file for indigopaas.orchestrator
- name: "Check input variables"
  fail:
    msg: "Change the password: you are using <<changeit>> as value for one or more variables (orchestrator_mysql_root_password, orchestrator_mysql_password) " 
  when: item == "changeit"
  with_items:
    - "{{orchestrator_mysql_root_password}}"
    - "{{orchestrator_mysql_password}}"


- name: "Set DB HOST"
  set_fact: orchestrator_mysql_host=127.0.0.1
      
- name: "create directory path to store the configuration files and persistent data" 
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ orchestrator_mysql_data_dir }}"


- name: "Create mysql container env file"
  template:
    src=mysql-env.j2 dest="{{ orchestrator_conf_dir }}/.mysqlenv"


- name: Start mysql and create the deployments DB
  docker_container: 
    name: orchestrator-mysql
    image: "{{ orchestrator_mysql_image }}"
    detach: true
    state: started
    network_mode: host
#    published_ports:
#     - 3306:3306
    volumes:
    - "{{ orchestrator_mysql_data_dir }}:/var/lib/mysql"
    restart_policy: always
    env_file: "{{ orchestrator_conf_dir }}/.mysqlenv"


- name: wait for mysql to be up and running 
  wait_for: 
     host: "localhost" 
     port: "3306"
     delay: 20
     timeout: 600
     connect_timeout: 10

- name: install MySQL-python
  pip: 
    name: PyMySQL
    state: present

- name: create the workflow DB
  mysql_db:
    login_host: "{{orchestrator_mysql_host}}"
    login_password: "{{orchestrator_mysql_root_password}}"
    login_user: root
    name: "{{orchestrator_workflow_dbname}}" 
    state: present

- name: add privileges to orchestrator db user
  mysql_user:
    append_privs: yes
    host: "%"
    login_host: "{{orchestrator_mysql_host}}"
    login_password: "{{orchestrator_mysql_root_password}}"
    login_user: root
    name: "{{orchestrator_mysql_user}}"
    password: "{{orchestrator_mysql_password}}"
    priv: "{{orchestrator_workflow_dbname}}.*:ALL"
    state: present


