---
# tasks file for indigopaas.orchestrator
- name: "Check input variables"
  fail:
    msg: "Change the password: you are using <<changeit>> as value for one or more variables (orchestrator_mysql_password) " 
  when: item == "changeit"
  with_items:
    - "{{orchestrator_mysql_password}}"


- name: "create directory path to store the configuration files and persistent data" 
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ orchestrator_conf_dir }}"
    - "{{ orchestrator_conf_dir}}/trusted_certs"

- include: database.yml 
  when: orchestrator_db_host is not defined

- set_fact: 
    orchestrator_mysql_host: "{{ orchestrator_db_host }}"
  when: orchestrator_db_host is defined  

- debug:
    var: orchestrator_mysql_host      

- name: "Create Orchestrator container env file"
  template:
    src=orchestrator-env.j2 dest="{{ orchestrator_conf_dir }}/.orchenv"


- name: "Create the oidc conf file"
  template: 
    src=orchestrator-application.j2 dest="{{ orchestrator_conf_dir }}/application.yml"

- set_fact:
    volumes_to_mount:
       - "{{orchestrator_conf_dir}}/application.yml:/orchestrator/application.yml"
       - "{{orchestrator_conf_dir}}/trusted_certs:/orchestrator/trusted_certs"


- name: Start Orchestrator container
  docker_container:
    name: orchestrator
    image: "{{ orchestrator_image }}"
    pull: true
    detach: true
    state: started
    network_mode: "host"
    volumes: "{{volumes_to_mount}}"
    restart_policy: always
    env_file: "{{ orchestrator_conf_dir }}/.orchenv"

