---
- name: Install letsencrypt
  apt: name=letsencrypt state=present update_cache=true
  tags:
    - nginx

- name: Create letsencrypt certificate
  shell: letsencrypt certonly -n --standalone -m {{ iam_admin_email }} --agree-tos -d {{ iam_fqdn }}
  args:
    creates: /etc/letsencrypt/live/{{ iam_fqdn }}
  tags:
    - nginx

- name: "Create nginx conf file"
  template:
    src=nginx.conf.j2 dest="{{ iam_conf_dir }}/nginx-default.conf"
  tags:
    - nginx

- name: start nginx container for IAM
  docker_container:
    name: iam-proxy
    image: "{{ nginx_image }}"
    detach: true
    state: started
    network_mode: "host"
    volumes:
    - "{{ iam_conf_dir }}/nginx-default.conf:/etc/nginx/conf.d/default.conf"
    - "{{ iam_ssl_cert_path }}:/etc/nginx/cert.crt"
    - "{{ iam_ssl_key_path }}:/etc/nginx/cert.key"
    restart_policy: always
  tags:
    - nginx
  
