---
#- name: Check python is installed
#  raw:  test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
#  changed_when: false

- name: Update apt cache
  apt:
    update_cache: yes

- name: Download docker role
  local_action: command ansible-galaxy install -p /etc/ansible/roles indigo-dc.docker,2.1.2-beta
  changed_when: false

- include_role: 
    name: indigo-dc.docker


