---
- name: Deploy IAM service
  hosts: iam
  become: yes
  gather_facts: false
  pre_tasks:
    - name: Check python is installed
      raw:  test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false
    - name: Gathering Facts
      setup:
  roles:
    - iam
