---
- hosts: monitoring
  become: yes
  gather_facts: false
  pre_tasks:
    - name: Check python is installed
      raw:  test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false
    - name: Gathering Facts
      setup:

- hosts: monitoring_server
  become: yes
  roles:
    - { role: monitoring, monitoring_node_type: "server" }

- hosts: monitoring_agent
  become: yes
  roles:
   - { role: monitoring, monitoring_node_type: "agent" }
