---
- name: "create directory path to store the configuration files"
  file:
    path: "{{ vault_conf_dir }}/certs"
    state: directory

- name: "Copy the certificate"
  copy:
    src: "{{ vault_ssl_cert_file }}"
    dest: "{{ vault_conf_dir }}/certs/cert.pem"

- name: "Copy the key"
  copy:
    src: "{{ vault_ssl_key_file }}"
    dest: "{{ vault_conf_dir }}/certs/key.pem"
    
- set_fact:
    vault_cert_file_path: "{{ vault_conf_dir }}/certs/cert.pem"
    vault_key_file_path: "{{ vault_conf_dir }}/certs/key.pem"
