---
# tasks file for vault
- name: "create directory path to store the configuration files"
  file:
    path: "{{ vault_conf_dir }}"
    state: directory
  tags:
    - vault

- name: "create vault configuration file"
  template:
    src: config.hcl.j2
    dest: "{{ vault_conf_dir }}/config.hcl"
  notify:
    - restart vault  
  tags:
    - vault

- include: letsencrypt.yml
  when: vault_letsencrypt|bool

- include: certs.yml
  when: not vault_letsencrypt|bool  

- name: "Install docker-compose"
  pip: name="docker-compose" state="present"

- name: "Create the docker-compose file"
  template: src="docker-compose.j2" dest="{{ vault_conf_dir }}/docker-compose.yml"
  notify:
    - restart vault

- name: "Start the service"
  docker_service:
    project_src: "{{ vault_conf_dir }}"
    state: present

      
