---
# tasks file for indigopaas.slam

- name: "Check input variables"
  fail:
    msg: "Change the password: you are using <<changeit>> as value for one or more variables (im_mysql_root_password, im_mysql_password) " 
  when: item == "changeit"
  with_items:
    - "{{im_mysql_root_password}}"
    - "{{im_mysql_password}}"


- name: "create directory path to store the configuration files" 
  file:
    path: "{{ im_conf_dir }}"
    state: directory
    mode: 0755

- name: "Create mysql container env file"
  template:
    src=mysql-env.j2 dest="{{ im_conf_dir }}/.mysqlenv"

- name: Copy ansible.cfg
  copy: src="files/ansible.cfg" dest="{{ im_conf_dir }}/ansible.cfg" 

- name: Start mysql
  docker_container: 
    name: mysql
    image: "{{ im_mysql_image }}"
    detach: true
    state: started
    network_mode: "host"
    volumes:
    - "{{ im_mysql_data_dir }}:/var/lib/mysql"
    restart_policy: always
    env_file: "{{ im_conf_dir }}/.mysqlenv"

- name: wait for mysql to be up and running 
  wait_for: 
     host: "localhost" 
     port: "3306"
     delay: 20
     timeout: 600
     connect_timeout: 10

- name: "Create IM container env file"
  template:
    src=im-env.j2 dest="{{ im_conf_dir }}/.imenv"


- name: Modify IM config file 
  include: im_config.yml

- name: Start IM container
  docker_container:
    name: im
    image: "{{ im_image }}"
    detach: true
    state: started
    network_mode: "host"
    volumes:
    - "{{im_log_dir}}:/var/log/im"
    - "{{im_conf_dir}}/im.cfg:/etc/im/im.cfg"
    - "{{im_conf_dir}}/ansible.cfg:/etc/ansible/ansible.cfg"
    restart_policy: always
    env_file: "{{ im_conf_dir }}/.imenv"

