---

- name: "Install docker-compose"
  pip: name="docker-compose" state="present"

- name: "create directory path to store the configuration files"
  file:
    path: "{{ proxy_conf_dir }}"
    state: directory
    mode: 0755

- include: letsencrypt.yml
  when: proxy_use_letsencrypt|bool

- include: nginx.yml
  when: not proxy_use_letsencrypt|bool


